# In order to set up the Discord bot's message, use the command "$setup" in Discord.
# It will create a new message that will be edited with the status of the Minecraft Server.
# Make sure the bot has permission "EMBED_LINKS", "SEND_MESSAGES" and "VIEW_CHANNEL"
# ServerStatus.NameFormat Default placeholders: https://github.com/vaporrrr/BTEDiscordAddon (PlaceHolder API is supported)
# Stats.Minecraft.Description Default placeholders: https://github.com/vaporrrr/BTEDiscordAddon (PlaceHolder API is supported)
# Stats.Team.Description Default placeholders: https://github.com/vaporrrr/BTEDiscordAddon (PlaceHolder API is supported)
ServerStatus:
  Title: "Minecraft Server"
  IconURL: "https://i.imgur.com/dhYpMGQ.gif"
  ChannelID: 000000000000000000
  MessageID: 000000000000000000
  OfflineMessage: "Sorry for the inconvenience."
  NameFormat: "$player_name_with_afk_status$ $discord_mention$"
  Colors:
    PlayersOnline: a1ee33
    NoPlayersOnline: a1ee33
    Offline: 962d2d
AutoAfkInSeconds: 30
DiscordCommandsPrefix: $
Linking:
  ChannelID: 000000000000000000
  DelayBeforeDeleteMsgInSeconds: 5
MinecraftCommands:
  afk:
    CooldownInSeconds: 10
DiscordCommands:
  setup:
    Enabled: true
    Permissions:
      Roles:
        - 000000000000000000
  linked:
    Enabled: true
    Permissions:
      Roles:
        - 000000000000000000
  online:
    Enabled: true
    Title: "Minecraft Server"
    Permissions:
      Roles:
        - 000000000000000000
Schematics:
  Upload:
    ChannelID: 00000000000000000
    MaxSizeInKB: 8192
  Download:
    ChannelID: 00000000000000000
Stats:
  Minecraft:
    Enabled: true
    IntervalInSeconds: 120
    ChannelID: 00000000000000000
    MessageID: 00000000000000000
    Description:
      - "**Last Updated**: <t:$current_unix$:R>"
      - "**Unique Players Joined**: `$unique_players_joined$`"
      - "**Linked Players**: `$linked_players$`"
      - "**Memory**: $memory$"
      - "**Uptime**: $uptime$"
    GroupNames:
      - Default
  Team:
    Enabled: true
    IntervalInSeconds: 300
    ChannelID: 00000000000000000
    MessageID: 00000000000000000
    BTEWebsiteAPIKey: ""
    Description:
      - "**Last Updated**: <t:$current_unix$:R>"
      - "**-- BTE Website --**"
      - "**Members**: `$bte_team_members$`"
      - "**Leaders**: `$bte_team_leaders$`"
      - "**Co-Leaders**: `$bte_team_co-leaders$`"
      - "**Reviewers**: `$bte_team_reviewers$`"
      - "**Builders**: `$bte_team_builders$`"
      - "**Team/Project Locations**: `$bte_team_locations$`/`$bte_project_locations$`"
      - "**Pending Applications**: `$bte_team_applications_pending$`"
      - "**-- Discord --**"
      - "**Guild Created**: <t:$guild_age_unix$:R>"
      - "**Members**: `$guild_members$`/`$guild_member_max$`"
      - "**Categories**: `$guild_categories$`"
      - "**Voice Channels**: `$guild_channel_voice$`"
      - "**Text Channels**: `$guild_channel_text$`"
      - "**Store Channels**: `$guild_channel_store$`"
      - "**Channels**: `$guild_channels$`"
      - "**Roles**: `$guild_roles$`"
      - "**Emotes**: `$guild_emotes$`/`$guild_emote_max$`"
      - "**Boosts**: `$guild_boosts$`"
      - "**Boosters**: `$guild_boosters$`"
    RoleIDS:
      - 00000000000000000
