# In order to set up the Discord bot's message, use the command "$setup" in Discord.
# It will create a new message that will be edited with the status of the Minecraft Server.
# Make sure the bot has permission "EMBED_LINKS", "SEND_MESSAGES" and "VIEW_CHANNEL"
# NameFormat placeholder options: %username% %discord-mention% %discord-tag% %discord-username% %discord-id%
ServerStatus:
  Title: "Minecraft Server"
  IconURL: "https://i.imgur.com/dhYpMGQ.gif"
  ChannelID: 00000000000000000
  MessageID: 000000000000000000
  OfflineMessage: "Sorry for the inconvenience."
  NameFormat: "%username% %discord-mention%"
  Colors:
    PlayersOnline: a1ee33
    NoPlayersOnline: a1ee33
    Offline: 962d2d

AutoAfkInSeconds: 10

LinkedCommandGuildID: 00000000000000000
DiscordPrefix: $
UploadSchematicsChannelID: 00000000000000000
DownloadSchematicsChannelID: 00000000000000000
LinkAccountChannelID: 00000000000000000
DelayBeforeDeleteLinkAccountMessageInSeconds: 5

StatsEnabled: true
MinecraftStatsEditIntervalInSeconds: 10
MinecraftStatsMessageID: 00000000000000000
MinecraftStatsGroupNames:
  - Builder
  - Default

TeamStatsEditIntervalInSeconds: 10
TeamStatsMessageID: 00000000000000000
TeamStatsRoleIDS:
  - 0
  - 0
