# In order to set up the Discord bot's message, use the command "$setup" in Discord.
# It will create a new message that will be edited with the status of the Minecraft Server.
# Make sure the bot has permission "EMBED_LINKS", "SEND_MESSAGES" and "VIEW_CHANNEL"

# Displayed at top of embed
ServerIP: "buildtheearth.net"

LinkedCommandGuildID: "0"

ChannelID: "0"

MessageID: "0"

OfflineMessage: "Read the announcements channel for more information"

DiscordPrefix: '$'

UploadSchematicsChannelID: "0"

DownloadSchematicsChannelID: "0"

LinkAccountChannelID: "0"

DelayBeforeDeleteLinkAccountMessageInSeconds: 5

MinecraftStatsEditIntervalInSeconds: 10

TeamStatsEditIntervalInSeconds: 10

TeamStatsRoleID: "0"

MinecraftStatsMessageID: "0"

TeamStatsMessageID: "0"

BuilderRoleID: "0"

NoPlayersHexColor: "a1ee33"