# IMPORTANT
# Make sure the bot has permission "EMBED_LINKS", "SEND_MESSAGES" and "VIEW_CHANNEL"

# In order to set up the Discord bot's message, use the command "$setup" in Discord.
# It will create a new message that will be edited with the status of the Minecraft Server.
# Provided placeholders: https://github.com/vaporrrr%btediscordAddon (PlaceHolder API is supported)
ServerStatus:
  Title: Minecraft Server
  IconURL: https://i.imgur.com/dhYpMGQ.gif
  ChannelID: 000000000000000000
  MessageID: 000000000000000000
  OfflineMessage: Sorry for the inconvenience.
  NameFormat: $player_name_with_afk_status$ $discord_mention$
  # Hex color values
  Colors:
    PlayersOnline: a1ee33
    NoPlayersOnline: a1ee33
    Offline: 962d2d

# How long a player must be doing nothing for them to go afk
AutoAfkInSeconds: 30

DiscordCommandsPrefix: $
DiscordCommands:
  setup:
    Enabled: true
    Permissions:
      Roles:
        - 000000000000000000
      Users:
        - 000000000000000000
  linked:
    Enabled: true
    Permissions:
      Roles:
        - 000000000000000000
      Users:
        - 000000000000000000
  online:
    Enabled: true
    Title: Minecraft Server
    Permissions:
      Roles:
        - 000000000000000000
      Users:
        - 000000000000000000
Linking:
  ChannelID: 000000000000000000
  DelayBeforeDeleteMsgInSeconds: 5
Schematics:
  Upload:
    ChannelID: 00000000000000000
    MaxSizeInKB: 8192
  Download:
    ChannelID: 00000000000000000

MinecraftCommands:
  afk:
    CooldownInSeconds: 10

# Provided placeholders: https://github.com/vaporrrr%btediscordAddon (PlaceHolder API is supported)
Stats:
  Minecraft:
    Enabled: true
    IntervalInSeconds: 120
    ChannelID: 00000000000000000
    MessageID: 00000000000000000
    Description:
      - '**Last Updated**: <t:%bted_time_now_unix%:R>'
      - '**Unique Players Joined**: `%bted_unique_players_joined%`'
      - '**Linked Players**: `%bted_linked_players%`'
      - '**Memory**: %bted_memory%'
      - '**Uptime**: %bted_uptime%'
  # BTEWebsiteAPIKey can be obtained from https://github.com/BuildTheEarth/build-team-api#getting-your-api-key
  Team:
    Enabled: true
    IntervalInSeconds: 300
    ChannelID: 00000000000000000
    MessageID: 00000000000000000
    BTEWebsiteAPIKey: ''
    Description:
      - '**Last Updated**: <t:%bted_time_now_unix%:R>'
      - '**-- BTE Website --**'
      - '**Members**: `%bted_website_members%`'
      - '**Leaders**: `%bted_website_leaders%`'
      - '**Co-Leaders**: `%bted_website_co-leaders%`'
      - '**Reviewers**: `%bted_website_reviewers%`'
      - '**Builders**: `%bted_website_builders%`'
      - '**Team/Total Locations**: `%bted_website_locations_team%`/`%bted_website_locations_total%`'
      - '**Pending Applications**: `%bted_website_applications_pending%`'
      - '**-- Discord --**'
      - '**Guild Created**: `%bted_guild_creation_date%`'
      - '**Members**: `%bted_guild_members%`/`%bted_guild_member_max%`'
      - '**Categories**: `%bted_guild_categories%`'
      - '**Voice Channels**: `%bted_guild_channel_voice%`'
      - '**Text Channels**: `%bted_guild_channel_text%`'
      - '**Store Channels**: `%bted_guild_channel_store%`'
      - '**Channels**: `%bted_guild_channels%`'
      - '**Roles**: `%bted_guild_roles%`'
      - '**Emotes**: `%bted_guild_emotes%`/`%bted_guild_emote_max%`'
      - '**Boosts**: `%bted_guild_boosts%`'
      - '**Boosters**: `$%bted_guild_boosters%`'
      - '**Owner**: %bted_guild_owner_mention% (Status: %bted_guild_owner_status%)'
