# In order to set up the Discord bot's message, use the command "$setup" in Discord.
# It will create a new message that will be edited with the status of the Minecraft Server.
# Make sure the bot has permission "EMBED_LINKS", "SEND_MESSAGES" and "VIEW_CHANNEL"
# NameFormat Default placeholders: %player_name% %player_name_with_afk_status% %btedaddon_user_mention% %btedaddon_user_tag% %btedaddon_user_username% %btedaddon_user_id% (PlaceHolder API is supported)
ServerStatus:
  Title: "Minecraft Server"
  IconURL: "https://i.imgur.com/dhYpMGQ.gif"
  ChannelID: 000000000000000000
  MessageID: 000000000000000000
  OfflineMessage: "Sorry for the inconvenience."
  NameFormat: "%player_name_with_afk_status% %btedaddon_user_mention%"
  Colors:
    PlayersOnline: a1ee33
    NoPlayersOnline: a1ee33
    Offline: 962d2d
AutoAfkInSeconds: 30
DiscordCommandsPrefix: $
Linking:
  ChannelID: 000000000000000000
  DelayBeforeDeleteMsgInSeconds: 5
MinecraftCommands:
  afk:
    CooldownInSeconds: 10
DiscordCommands:
  setup:
    Enabled: true
    Permissions:
      Roles:
        - 000000000000000000
  linked:
    Enabled: true
    Permissions:
      Roles:
        - 000000000000000000
  online:
    Enabled: true
    Permissions:
      Roles:
        - 000000000000000000
Schematics:
  Upload:
    ChannelID: 00000000000000000
    MaxSizeInKB: 8192
  Download:
    ChannelID: 00000000000000000
Stats:
  Minecraft:
    Enabled: true
    IntervalInSeconds: 120
    ChannelID: 00000000000000000
    MessageID: 00000000000000000
    GroupNames:
      - Builder
      - Default
  Team:
    Enabled: true
    IntervalInSeconds: 300
    ChannelID: 00000000000000000
    MessageID: 00000000000000000
    RoleIDS:
      - 00000000000000000
