# In order to set up the Discord bot's message, use the command "$setup" in Discord.
# It will create a new message that will be edited with the status of the Minecraft Server.
# Make sure the bot has permission "EMBED_LINKS", "SEND_MESSAGES" and "VIEW_CHANNEL"

# Displayed at top of embed
ServerIP: "buildtheearth.net"
LinkedCommandGuildID: "0"
ChannelID: "0"
MessageID: "0"
OfflineMessage: "Read the announcements channel for more information"
NoPlayersHexColor: "a1ee33"

DiscordPrefix: '$'
UploadSchematicsChannelID: "0"
DownloadSchematicsChannelID: "0"
LinkAccountChannelID: "0"
DelayBeforeDeleteLinkAccountMessageInSeconds: 5

MinecraftStatsEditIntervalInSeconds: 10
MinecraftStatsMessageID: "0"
MinecraftStatsGroupNames:
  - "Builder"
  - "Default"

TeamStatsEditIntervalInSeconds: 10
TeamStatsMessageID: "0"
TeamStatsRoleIDS:
  - "0"
  - "0"
