main: me.vapor.discordplus.Main
name: DiscordPlus
depend: [DiscordSRV, WorldEdit, Essentials]
version: 1.4.0-SNAPSHOT
author: VapoR
commands:
  ds-update:
    description: Updates the Status Embed in Discord
    usage: /ds-update
    permission: ds.admin.update
  ds-reload:
    description: Reloads Config
    usage: /ds-reload
    permission: ds.admin.config