main: ${project.groupId}.${project.artifactId}.${project.name}
name: ${project.name}
depend: [DiscordSRV, WorldEdit, LuckPerms]
version: ${project.version}
author: VapoR
commands:
  ds-update:
    description: Updates the Status Embed in Discord
    usage: /ds-update
    permission: ds.admin.update
  ds-reload:
    description: Reloads Config
    usage: /ds-reload
    permission: ds.admin.config