main: ${project.groupId}.${project.artifactId}.${project.name}
name: ${project.name}
depend: [DiscordSRV, WorldEdit, LuckPerms]
softdepend: [PlaceholderAPI]
version: ${project.version}
author: VapoR
commands:
  bted-update:
    description: Updates the Status Embed in Discord
    usage: /bted-update
    permission: bted.admin.update
  bted-reload:
    description: Reloads Config
    usage: /bted-reload
    permission: bted.admin.config
  afk:
    description: Toggles afk status
    usage: /afk
    permission: bted.command.afk
permissions:
  bted.*:
    description: Wildcard
    children:
      bted.admin: true
      bted.admin.update: true
      bted.admin.reload: true
      bted.command: true
      bted.command.afk: true
  bted.admin.*:
    description: All "admin" permissions
    children:
      bted.admin.update: true
      bted.admin.reload: true
  bted.admin.update:
    description: Update Server Status message
  bted.admin.reload:
    description: Reload config
  bted.command.*:
    description: All general commands
    children:
      bted.command.afk: true
  bted.command.afk:
    description: Allows usage of /afk
